#!/usr/bin/python3
# -*-coding:Utf-8 -*

import os
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait




nav = webdriver.Firefox()
nav.get('')
