#!/usr/bin/python3
# -*-coding:Utf-8 -*

while 1 :
    lettre= input("tapez Q si vous voulez arreter, C sinon")
    if lettre = 'Q' or 'q' :
        print ("Au revoir, Merci !")
        break
    elif lettre = 'C' or 'c' :
        print ("et zeeeee repartiiiiii")
